# ===============================
# Database Configuration
# ===============================
# src/main/resources/application.yml

spring:
  datasource:
    url: jdbc:mysql://metro.proxy.rlwy.net:27575/railway
    username: root
    password: izQBaLJzcXzAkLsoQkCWdSGmCaaqBSHO
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ===============================
# Logging
# ===============================
logging:
  level:
    org.springframework.security: debug

# ===============================
# Project Config
# ===============================
project:
  image: images/

# ===============================
# JWT Security Key
# ===============================
jwt_secret: cl$ksc^nas%lkdm!cz@xclk#as&dmka;s28*392da%jskd#n9827@3498%

# ===============================
# Swagger OpenAPI
# ===============================
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: false
